### PR TITLE
MDMP v1.1 - The pf edition

### PR DESCRIPTION
**Pull request by AlexKornitzer**
This build adds the cool pf file parsing support to the MDMP plugin. For example:
```
pf.mdmp_location_descriptor dd DataSize RVA
pf.mdmp_location_descriptor64 qq DataSize RVA
pf.mdmp_memory_descriptor q? StartOfMemoryRange (mdmp_location_descriptor)Memory
pf.mdmp_memory_descriptor64 qq StartOfMemoryRange DataSize
pf.mdmp_vs_fixedfileinfo ddddddddddddd dwSignature dwStrucVersion dwFileVersionMs dwFileVersionLs dwProductVersionMs dwProductVersionLs dwFileFlagsMask dwFileFlags dwFileOs dwFileType dwFileSubtype dwFileDateMs dwFileDateLs
pf.mdmp_string dZ Length Buffer
pf.mdmp_header [4]zddddt[8]B Signature Version NumberOfStreams StreamDirectoryRVA CheckSum TimeDateStamp (mdmp_type)Flags
pf.mdmp_directory [4]E? (mdmp_stream_type)StreamType (mdmp_location_descriptor)Location
pf.mdmp_thread ddddq?? ThreadId SuspendCount PriorityClass Priority Teb (mdmp_memory_descriptor)Stack (mdmp_location_descriptor)ThreadContext
pf.mdmp_thread_list d[1]? NumberOfThreads (mdmp_thread)Threads
pf.mdmp_module qddtd???qq BaseOfImage SizeOfImage CheckSum TimeDateStamp ModuleNameRVA (mdmp_vs_fixedfileinfo)VersionInfo (mdmp_location_descriptor)CvRecord (mdmp_location_descriptor)MiscRecord Reserved0 Reserved1
pf.mdmp_module_list d[5]? NumberOfModule (mdmp_module)Modules
pf.mdmp_memory64_list qq[53]? NumberOfMemoryRanges BaseRva (mdmp_memory_descriptor64)MemoryRanges
pf.mdmp_memory_info qq[4]Edq[4]E[4]E[4]Ed BaseAddress AllocationBase (mdmp_page_protect)AllocationProtect __Alignment1 RegionSize (mdmp_mem_state)State (mdmp_page_protect)Protect (mdmp_mem_type)Type __Alignment2
pf.mdmp_memory_info_list ddq[77]? SizeOfHeader SizeOfEntry NumberOfEntries (mdmp_memory_info)MemoryInfo
pf.mdmp_exception [4]E[4]Eqqdd[15]q (mdmp_exception_code)ExceptionCode (mdmp_exception_flags)ExceptionFlags ExceptionRecord ExceptionAddress NumberParameters __UnusedAlignment ExceptionInformation
pf.mdmp_exception_stream dd?? ThreadId __Alignment (mdmp_exception)ExceptionRecord (mdmp_location_descriptor)ThreadContext
pf.mdmp_system_info [2]EwwbBddd[4]Ed[2]Ew[2]q (mdmp_processor_architecture)ProcessorArchitecture ProcessorLevel ProcessorRevision NumberOfProcessors (mdmp_product_type)ProductType MajorVersion MinorVersion BuildNumber (mdmp_platform_id)PlatformId CsdVersionRva (mdmp_suite_mask)SuiteMask Reserved2 ProcessorFeatures
pf.mdmp_misc_info d[4]Bdtttddddd SizeOfInfo (mdmp_misc1_flags)Flags1 ProcessId ProcessCreateTime ProcessUserTime ProcessKernelTime ProcessorMaxMhz ProcessorCurrentMhz ProcessorMhzLimit ProcessorMaxIdleState ProcessorCurrentIdleState
```

In addition to these changes PE bins will be parsed into their respective sections as noted here #79 
```
Quick little update: modules will now be split into subsections so that we can easily see their contents. As a result there should be fewer strings for `iz`.
...
```

I believe that this version is now feature complete and cannot be improved (I think) until changes have been applied to pe_*.c and r2 core. Therefore the roadmap now is as follows:
PE changes:
- Fix memory leaks
- Complete symbol support

Core changes:
- Parsing of all debug info.
- Proper support for the memory section.

### CODE REVIEW

**Comment by Maijin** [comment]
This broke r2pm for mdmp -> https://travis-ci.org/radare/radare2-extras

**Comment by AlexKornitzer** [comment]
Yeah I am a bit confused about that, surely if it builds with make agains r2 v1.0 is should be fine in travis. Or is that not entirely how it works? Just done a test and it does not build on my MacOS machine using r2pm.
```
rm -f p/*.dylib
cd p ; make bin_mdmp.dylib
make[1]: *** No rule to make target `bin_mdmp.dylib'.  Stop.
make: *** [mdmp] Error 2
```

**Comment by Maijin** [comment]
If you have some dependancy within r2pm please add them in mdmp r2pm -> https://github.com/radare/radare2-pm/blob/master/db/mdmp (dlang is also available via r2pm)

**Comment by Maijin** [comment]
also upgrade travis.yml then

**Comment by AlexKornitzer** [comment]
It isn't that it is a dependency, it due to the fact that the make file for bin extras is not setup correctly. You can only build all formats by running make dlang, it is not possible to build just one.

**Comment by AlexKornitzer** [comment]
I am happy to patch up the Makefile.acr if you wish but I am not at all familiar with it.

**Comment by Maijin** [comment]
Well I sent you the script for r2pm mdmp :) Nothing really more complex than this

**Comment by AlexKornitzer** [comment]
Right got you, i'll get that fixed ASAP.

**Comment by Maijin** [comment]
💛

**Comment by AlexKornitzer** [comment]
Done see #82, hopefully that should be working now. I tried running through the script manually and hit no errors.

**Pull request merged**
