### PR TITLE
Added bin_swf

### PR DESCRIPTION
**Pull request by xarkes**
I added bin_swf (no asm/anal yet but that's a start, and it only supports not compressed SWF)

### CODE REVIEW

**Comment by xarkes** [comment]
`R2PM_BEGIN

R2PM_GIT "https://github.com/xarkes/radare2-extras"
R2PM_DESC "[r2-bin] SWF / Flash disassembler" 

R2PM_INSTALL() {
	./configure --prefix="${R2PM_PREFIX}"
	cd libr/bin/p
	make bin_swf.so
	cp -f bin_swf.${LIBEXT} "${R2PM_PLUGDIR}"
}

R2PM_UNINSTALL() {
	rm -f "${R2PM_PLUGDIR}"/*swf*
}

R2PM_END
`
This is the radare2/binr/r2pm/d/swf file I use if you want to install it with r2pm -i swf

**Comment by radare** [comment]
Send another pr in the radare repo with this r2pm pkg

**Comment by xarkes** [comment]
Updated.

**Comment by radare** [comment]
Thanks! Looks good now!

**Pull request closed without merging**
