### PR TITLE
MDMP - r2 v1.7 Compatability

### PR DESCRIPTION
**Pull request by AlexKornitzer**
1. This brings the PE headers in line with r2 v1.7.
2. This fixes a horrible typo that has prevented the regression tests from running.

As a result the regression tests for mdmp do not pass at this moment in time.

First thing to check are the regression tests now running. Next is to work out what has broken the tests.

### CODE REVIEW

**Comment by AlexKornitzer** [comment]
Need to bump to v1.7 then continue.

**Comment by AlexKornitzer** [comment]
Found a possible cause for why the tests are failing, will comment once found and fixed.

**Comment by radare** [comment]
so if its not passing, i’ll wait until the PR is green

**Comment by AlexKornitzer** [comment]
SkUaTeR latest PR on the core fixed the majority of the bugs, there still seems to be a bug with PLT resolving.

**Comment by AlexKornitzer** [comment]
This is now ready for merging. The last test will no pass until the PR in r2-regressions is accepted.

**Comment by radare** [comment]
thanks!

**Pull request merged**
