### PR TITLE
[WIP] Apollo Guidance Computer disassembly

### PR DESCRIPTION
**Pull request by ibabushkin**
I ported the AGC disassembler from [yaAGC](https://github.com/alfonsokim/apollo-guidance-computer/blob/master/yaAGC/agc_disassembler.c) to work as a plugin. However, some open issues remain:

* Is internal state (which is required due to some details of the AGC architecture) acceptable? More specifically, do calls to `disassemble()`, as exposed by the plugin, happen in the order the instructions are encountered in? If not, are there any ways to decode multiple instructions at once? I can elaborate on this issue if needed.
* The assembler and emulator components still need to be implemented.

### CODE REVIEW

**Comment by Maijin** [comment]
What about anal?

**Comment by ibabushkin** [comment]
This also needs to be done yet, thanks for the reminder.

**Comment by Maijin** [comment]
Could you add a r2pm rule so it can be installed via `r2pm` command like the other extensions ? See https://github.com/radare/radare2-pm

**Comment by radare** [comment]
And esil. Which ahould be the piece that keeps the state for emulation. Is there a way to identify those binaries? Some kind of magic header or pattern? This will be useful for an rbin plugin to automatically set the arch from there.

Can you provice binaries? Adding support for assembling will be also nice, so it will enable to use rasm2 to assemble such programs instead of yayul

**Comment by ibabushkin** [comment]
Well, there is no specific binary format, so as far as I know, we don't have a way of deciding deterministically that the binary is intended for the AGC. Moreover, it's just running a memory image, whose contents get handled a in a slightly more complicated manner, so we'd need some way to support bank addressing and whatnot. As for ESIL and a r2pm rule, as well as assembling, I will do that as soon as possible.

**Comment by XVilka** [comment]
@ibabushkin for bank addressing you can see libr/anal/p/anal_gb.c and libr/asm/p/asm_gb.c

**Comment by ibabushkin** [comment]
Thanks, I'll look into it. That way we should be able to support handling binary files as AGC memory images. At least if I find a way to modify memory contents before passing them to the disassembler.

**Comment by Maijin** [comment]
All those comments:

// read and bitwise or with write ...

Could be really useful in a describe file see `e asm.describe=true ; pd 10` or `?d mov` on x86 for example.

Here is an example of the file https://github.com/radare/radare2/blob/master/libr/asm/d/x86

**Comment by ibabushkin** [comment]
Good idea! I walked through the entire instruction set today and annotated the sources, which were pretty convoluted. That way it should be easier to write the ESIL implementation and anal plugin with that info all in one place.

**Comment by radare** [comment]
Looks good to merge! Looking forward the anal plugs!

**Comment by ibabushkin** [comment]
Great, any input on the initial questions regarding constraints of the implementation?

**Comment by Maijin** [comment]
Add bins in r2r for testing purposes please https://github.com/radare/radare2-regressions/tree/master/bins

**Comment by gareth8118** [comment]
Should `Makefile` and `config.mk` in the base directory really be in the commit? These have been submitted as new files and up until this point were generated by the configure step from `Makefile.acr` and `config.mk.acr` respectively.

**Comment by ibabushkin** [comment]
Whoops, that shouldn't be the case. Will fix in next PR.

**Comment by gareth8118** [comment]
Hey @ibabushkin , I just submitted a PR to fix it but if you want to make the same change then @radare can pick which one to use... cheers

**Pull request merged**
