### PR TITLE
MDMP - Support for breaking changes in the core (r2 1.3.0)

### PR DESCRIPTION
**Pull request by AlexKornitzer**
Brings in the new PE headers from the core.

Maybe one day we will be in the core and these minor PRs will not be needed, wink wink, nudge nudge :p

### CODE REVIEW

**Comment by Maijin** [comment]
@AlexKornitzer  Would be cool if you could join our telegram channel to discuss one of the GSOC task involving MDPM with the students CC @XVilka  - https://t.me/radare

**Comment by AlexKornitzer** [comment]
Yeah I can jump in on that.

**Comment by radare** [comment]
Why upgrading the pe headers if new definitions are not used anywhere? Is this thing fixing something?

**Comment by AlexKornitzer** [comment]
I was experiencing a segfault which I believe was due to the change in structure size rather than function prototypes this time round.

**Comment by radare** [comment]
👍

**Pull request merged**
