### PR TITLE
add iddlf, iddlg and iddd

### PR DESCRIPTION
**Pull request by P4N74**
Updated Readme too.
Can be merged!! :)

### CODE REVIEW

**Comment by Maijin** [comment]
Please add tests for all those commands in https://github.com/radare/radare2-regressions/tree/master/t.extras + modify the makefile like this one https://github.com/radare/radare2-regressions/blob/master/Makefile#L175 + add a r2pm packet https://github.com/radare/radare2-pm/tree/master/db + modify the travis here https://github.com/radare/radare2-extras/blob/master/.travis.yml

CC @radare This is really important

**Comment by radare** [comment]
Kernels are huge we already discussed to put them in a separate repo

**Comment by jpenalbae** [comment]
There is no need to test this kernels, this could be tested with any ELF containing DWARF info, or a small kernel module.

**Comment by P4N74** [comment]
I will add travis and regresssion test for any ELF with DWARF entries in r2-regressions repo :)

**Comment by Maijin** [comment]
yes ELF with dwarf that's not r2k related 👍

**Comment by radare** [comment]
can we merge this?

**Comment by P4N74** [comment]
No no. There is some issue in the way I am extracting size for functions (It is giving wrong values). I will fix it by today and update this PR.

**Comment by P4N74** [comment]
@radare I have added the size field to flags and rebased the commits. This can be merged now I guess.

**Comment by P4N74** [comment]
should I add r2pm package in https://github.com/radare/radare2-pm/blob/master/db/libdwarf itself? Since libdwarf was added in r2pm because of this only and so I think combining them won't be a problem. Or I can make r2pm/dwarf which calls r2pm -i libdwarf internally and then installs this plugin.

Also for compilation of libdwarf, libelf and zlib is required.

**Comment by jpenalbae** [comment]
I would rename that package and call it dwarf-parser or something like.

About libdwarf, I would check if libdwarf is already present through pkg-config. If not, build libdwarf and link it statically, otherwise link with the one already available.

**Pull request merged**
