### PR TITLE
x86_udis.mk: also pass LDFLAGS

### PR DESCRIPTION
**Pull request by ilovezfs**
Fixes https://github.com/radare/radare2-extras/issues/153.

### CODE REVIEW

**Comment by radare** [comment]
thanks!

**Comment by ilovezfs** [comment]
Thanks for the merge @radare!

**Comment by radare** [comment]
the r2e repo is not making travis happy. i should spend some time on this :{{ but nobody seems to care too much about r2e until they need to use it. Are you maintaining brew packages for 3rd party r2 plugins?

**Comment by ilovezfs** [comment]
@radare `bokken` is the only formula in Homebrew/homebrew-core that has a

```
depends_on "radare2"
```

so none that I am aware of.

**Pull request merged**
