### PR TITLE
Add pyc file format plugin

### PR DESCRIPTION
**Pull request by c0riolis**
radare2 issue #4228.

### CODE REVIEW

**Comment by jvoisin** [comment]
LGTM

**Comment by radare** [comment]
See comments, and i'll merge after those changes. Thanks!

**Comment by radare** [comment]
Also, it is important for bin plugins to implement the entrypoint and sections callbacks

**Comment by c0riolis** [comment]
@radare: Thanks for the review. Updated.
I've put a comment to explain why it's
```length < 8```
and not
```length < sizeof (magic)```
(I'm checking if the timestamp is present after the magic number).
Also, entrypoint, sections callbacks as well as disassembly are coming, I just wanted to break it into several commits so it's not a pain to review.
Thanks!

**Comment by radare** [comment]
cool! thanks

**Pull request merged**
